#!/usr/bin/env python
# coding:utf-8

s = set([])
print(s)
s.add("a")
s.add("b")
print(s)
s.add("a")
print(s)
print("\n")

t = set(["q", "w", "e", "r", "t"])
s.update(t)
print(s)
item = s.pop()
print(item)
print(s)
s.remove("q")
# if not a member, can raise KeyError
s.discard("w")
s.discard("q")
# if not a member, do nothing
print(s)
print("\n")

t.clear()
print("a" in s)
t = set(["e", "f", "t", "l"])
print(t)
q = set([])
q.update(s)
q.update(t)
print(q)
print(t.issubset(q))
print(q.issuperset(t))
print("\n")

print(s & t)
print(s.intersection(t))
print(s | t)
print(s.union(t))
print(s - t)
print(s.difference(t))
print(s.symmetric_difference(t))
print("\n")

q.clear()
q.add("l")
q.add("t")
print(s)
print(q)
q.intersection_update(s)
print(q)
q.difference_update(s)
print(q)
q.symmetric_difference_update(s)
print(q)
print("\n")

r = frozenset(["a", "b", "c", "d"])
print(r)
